# Site settings
title: Steinvoort.net
email: mark@steinvoort.net
description: Baasdesign Jekyll Template
# for live
baseurl: "/jekyll"
siteurl: "steinvoort.github.io/jekyll"

#for local
# baseurl: ""
# siteurl: "localhost:4000"

twitter_username: baasdesign
github_username:  Steinvoort

# Build settings #
markdown: kramdown
