# Site settings
title: Baasdesign Jekyll Template
email: info@baasdesign.nl
description: Baasdesign Jekyll Template
# for live
baseurl: "/jekyll"
siteurl: "steinvoort.github.io/jekyll"

#for local
# baseurl: ""
# siteurl: "localhost:4000"

twitter_username: baasdesign
github_username:  baasdesign

# Build settings #
markdown: kramdown
